"""
Canonical skill alias mappings for DataPulse.

Single source of truth — imported by both SkillsMapper (onboarding)
and extractor (market signal processing). Never duplicate alias
definitions across modules.
"""

# Keys: lowercase normalized input strings
# Values: canonical skill name (must match skills.name in DB)
SKILL_ALIASES: dict[str, str] = {
    # --- Python ecosystem ---
    "python3": "python",
    "python 3": "python",
    "py": "python",
    "python/software development": "python",
    "pyspark": "spark",
    "apache spark": "spark",
    "apache spark structured streaming": "spark",
    "scipy": "python",
    "pydantic": "python",
    "flask": "python",
    "jax": "pytorch",

    # --- SQL & Databases ---
    "postgres": "postgresql",
    "psql": "postgresql",
    "ms sql": "ms_sql_server",
    "sql server": "ms_sql_server",
    "mssql": "ms_sql_server",
    "t-sql": "ms_sql_server",
    "tsql": "ms_sql_server",
    "pl/sql": "oracle",
    "amazon redshift": "amazon_redshift",
    "hbase": "data_engineering",
    "redis": "data_engineering",
    "database design": "data_modeling",
    "database scaling and optimization": "data_modeling",
    "data warehouse": "data_modeling",
    "data warehouse design": "data_modeling",

    # --- BI & Visualization ---
    "pbi": "power_bi",
    "power bi": "power_bi",
    "powerbi": "power_bi",
    "excel/spreadsheet analytics": "excel",
    "google sheets": "excel",
    "business intelligence": "power_bi",
    "embedded analytics": "power_bi",
    "data analysis": "data_science",
    "data analytics": "data_science",
    "business analytics": "data_science",
    "data science": "data_science",
    "healthcare data analytics": "data_science",

    # --- Cloud & Infrastructure ---
    "amazon web services": "aws",
    "aws analytics": "aws",
    "aws glue": "aws",
    "aws lake formation": "aws",
    "aws lambda": "aws",
    "amazon athena": "aws",
    "amazon emr": "aws",
    "amazon kinesis": "aws",
    "amazon sagemaker": "aws",
    "amazon opensearch": "aws",
    "amazon opensearch service": "aws",
    "google cloud": "gcp",
    "google cloud platform (gcp)": "gcp",
    "google cloud run": "gcp",
    "google cloud ai hypercomputer": "gcp",
    "google cloud sensitive data protection": "gcp",
    "vertex ai": "gcp",
    "google vertex ai": "gcp",
    "microsoft azure": "azure",
    "azure ai": "azure",
    "azure data factory": "azure",
    "microsoft fabric": "microsoft_fabric",
    "cloud computing": "aws",
    "cloud security": "aws",

    # --- Data Engineering ---
    "etl": "etl_design",
    "elt": "etl_design",
    "etl/elt": "etl_design",
    "data pipelines": "etl_design",
    "data pipeline architecture": "etl_design",
    "real-time data pipelines": "etl_design",
    "zero-etl architecture": "etl_design",
    "no-code etl tools": "etl_design",
    "data engineering": "data_engineering",
    "data engineering tools": "data_engineering",
    "data infrastructure": "data_engineering",
    "data infrastructure management": "data_engineering",
    "data platform management": "data_engineering",
    "data extraction": "etl_design",
    "data transformation": "etl_design",
    "data integration": "etl_design",
    "cdc": "etl_design",
    "cdc (change data capture)": "etl_design",
    "analytics engineering": "analytics_engineering",
    "analytics": "analytics_engineering",
    "semantic layer": "analytics_engineering",
    "semantic models": "analytics_engineering",
    "data contracts": "data_governance",
    "data lineage": "data_governance",
    "data quality": "data_governance",
    "data quality management": "data_governance",
    "data quality and validation": "data_governance",
    "data catalog": "data_governance",
    "metadata management": "data_governance",
    "data observability": "data_observability",
    "data mesh": "data_mesh",
    "data products development": "data_mesh",
    "data product architecture": "data_mesh",
    "data product management": "data_mesh",
    "lakehouse architecture": "lakehouse",
    "apache iceberg": "apache_iceberg",
    "apache kafka": "apache_kafka",
    "kafka": "apache_kafka",
    "apache flink": "apache_kafka",
    "apache beam": "data_engineering",
    "apache airflow": "airflow",

    # --- AI / ML core ---
    "machine learning": "machine_learning",
    "ai/machine learning": "machine_learning",
    "algorithms & machine learning": "machine_learning",
    "deep learning": "deep_learning",
    "deep neural networks": "deep_learning",
    "reinforcement learning": "reinforcement_learning",
    "deep reinforcement learning": "reinforcement_learning",
    "multi-agent reinforcement learning": "reinforcement_learning",
    "reinforcement learning from human feedback": "reinforcement_learning",
    "rlhf (reinforcement learning from human feedback)": "reinforcement_learning",
    "proximal policy optimization": "reinforcement_learning",
    "meta-learning": "machine_learning",
    "unsupervised learning": "machine_learning",
    "federated learning": "machine_learning",
    "scikit-learn": "machine_learning",
    "sklearn": "machine_learning",
    "statistical modeling": "machine_learning",
    "bayesian statistics": "machine_learning",
    "machine learning engineering": "machine_learning",
    "machine learning operations": "mlops",
    "ml experiment tracking": "mlops",
    "ml inference serving": "mlops",
    "ai deployment/mlops": "mlops",
    "model deployment": "mlops",
    "model distillation": "fine_tuning",
    "model evaluation": "machine_learning",
    "machine learning evaluation": "machine_learning",
    "ai model evaluation": "machine_learning",
    "ai benchmarking & evaluation": "machine_learning",

    # --- Generative AI & LLMs ---
    "generative ai": "generative_ai",
    "generative models": "generative_ai",
    "ai": "generative_ai",
    "artificial intelligence": "generative_ai",
    "advanced ai": "generative_ai",
    "large language models": "llm_integration",
    "large language models (llms)": "llm_integration",
    "large language models (llm)": "llm_integration",
    "ai/large language models": "llm_integration",
    "language models": "llm_integration",
    "llm": "llm_integration",
    "llm engineering": "llm_integration",
    "llm integration": "llm_integration",
    "llm api integration": "llm_integration",
    "ai/llm": "llm_integration",
    "ai/llm engineering": "llm_integration",
    "ai/llm development": "llm_integration",
    "ai/llm integration": "llm_integration",
    "ai/llm application development": "llm_integration",
    "llms for analytics": "llm_integration",
    "llm-based analytics": "llm_integration",
    "foundation models": "llm_integration",
    "transformer models": "deep_learning",
    "transformer": "deep_learning",
    "transformers": "deep_learning",
    "transformer architecture": "deep_learning",
    "encoder-decoder language models": "deep_learning",
    "fine-tuning": "fine_tuning",
    "llm fine-tuning": "fine_tuning",
    "llm fine-tuning & post-training": "fine_tuning",
    "reinforcement fine-tuning": "fine_tuning",
    "gpt-4o fine-tuning": "fine_tuning",
    "machine learning model fine-tuning": "fine_tuning",
    "embedding models": "rag",
    "embeddings": "rag",
    "text embeddings": "rag",
    "vector databases": "vector_databases",
    "vector database": "vector_databases",
    "semantic search": "rag",
    "retrieval-augmented generation": "rag",
    "retrieval augmented generation": "rag",
    "retrieval-augmented generation (rag)": "rag",
    "retrieval augmented generation (rag)": "rag",
    "rag (retrieval-augmented generation)": "rag",
    "agentic rag": "rag",

    # --- AI Agents ---
    "ai agents": "ai_agents",
    "agentic ai": "ai_agents",
    "agentic ai development": "ai_agents",
    "ai agent development": "ai_agents",
    "ai coding agents": "ai_agents",
    "ai agent orchestration": "ai_agents",
    "autonomous agents": "ai_agents",
    "multi-agent systems": "ai_agents",
    "multi-agent ai": "ai_agents",
    "multi-agent ai systems": "ai_agents",
    "enterprise ai agents": "ai_agents",
    "agentic ai / autonomous ai agents": "ai_agents",
    "autonomous security agents / ai agents": "ai_agents",
    "ai data agents": "ai_agents",
    "llm agents": "ai_agents",
    "agent engineering": "ai_agents",
    "agent/tool orchestration": "ai_agents",
    "agentic coding": "ai_agents",
    "autonomous coding agents": "ai_agents",
    "ai agent tools": "ai_agents",
    "ai agent reliability": "ai_agents",
    "ai agent evaluation": "ai_agents",
    "ai agent security": "ai_agents",
    "ai agents for regulated industries": "ai_agents",
    "claude agent sdk": "ai_agents",
    "google agent development kit (adk)": "ai_agents",
    "mcp": "ai_agents",
    "model context protocol": "ai_agents",
    "model context protocol (mcp)": "ai_agents",

    # --- Specific AI products (map to parent concept) ---
    "chatgpt": "llm_integration",
    "chatgpt enterprise": "llm_integration",
    "chatgpt api": "llm_integration",
    "openai api": "llm_integration",
    "openai gpt": "llm_integration",
    "openai codex": "llm_integration",
    "openai o1": "llm_integration",
    "o1": "llm_integration",
    "o3-mini": "llm_integration",
    "gpt": "llm_integration",
    "gpt-2": "llm_integration",
    "gpt-3": "llm_integration",
    "gpt-3.5": "llm_integration",
    "gpt-3 api": "llm_integration",
    "gpt-4": "llm_integration",
    "gpt-4 api": "llm_integration",
    "gpt-4o": "llm_integration",
    "gpt-4o mini": "llm_integration",
    "gpt-4.1 and realtime api": "llm_integration",
    "gpt-4.5": "llm_integration",
    "gpt-5": "llm_integration",
    "gpt-5.2": "llm_integration",
    "gpt-5.3-codex": "llm_integration",
    "gpt-5.3-codex-spark": "llm_integration",
    "openai gpt-5.4": "llm_integration",
    "claude": "llm_integration",
    "claude ai": "llm_integration",
    "claude ai models": "llm_integration",
    "claude (large language model)": "llm_integration",
    "claude api": "llm_integration",
    "claude code": "llm_integration",
    "claude opus": "llm_integration",
    "gemini": "llm_integration",
    "gemini api": "llm_integration",
    "gemini 2.0 flash": "llm_integration",
    "gemma framework": "llm_integration",
    "llama": "llm_integration",
    "dall·e": "generative_ai",
    "dall·e api": "generative_ai",
    "sora": "generative_ai",
    "copilot": "llm_integration",
    "code generation": "llm_integration",
    "code completion": "llm_integration",
    "ai-assisted coding": "llm_integration",
    "ai-assisted development": "llm_integration",
    "ai-assisted software development": "llm_integration",
    "ai-assisted code generation": "llm_integration",
    "ai-augmented development": "llm_integration",
    "ai-native development": "llm_integration",
    "ai coding": "llm_integration",
    "ai coding assistants": "llm_integration",
    "ai code generation": "llm_integration",
    "ai programming": "llm_integration",
    "code review automation": "llm_integration",
    "vibe engineering": "llm_integration",
    "code interpreter": "llm_integration",

    # --- AI Safety & Governance ---
    "ai safety": "ai_safety",
    "ai safety evaluation": "ai_safety",
    "ai safety and preparedness": "ai_safety",
    "ai safety and model evaluation": "ai_safety",
    "ai safety and interpretability": "ai_safety",
    "ai safety and compliance": "ai_safety",
    "ai security": "ai_safety",
    "ai security testing": "ai_safety",
    "ai security research and vulnerability management": "ai_safety",
    "ai interpretability": "ai_safety",
    "ai interpretability and verification": "ai_safety",
    "neural network interpretability": "ai_safety",
    "model interpretability": "ai_safety",
    "machine learning interpretability": "ai_safety",
    "ai alignment": "ai_safety",
    "machine learning alignment": "ai_safety",
    "machine learning safety": "ai_safety",
    "machine learning security": "ai_safety",
    "ai watermarking": "ai_safety",
    "red teaming": "ai_safety",
    "responsible ai": "ai_safety",
    "ai governance": "ai_governance",
    "ai governance and compliance": "ai_governance",
    "ai governance & compliance": "ai_governance",
    "ai governance and regulation": "ai_governance",
    "enterprise ai governance": "ai_governance",
    "ai regulation": "ai_governance",
    "ai regulation and compliance": "ai_governance",
    "ai regulation/compliance": "ai_governance",
    "ai regulation (eu ai act)": "ai_governance",
    "eu ai act compliance": "ai_governance",
    "ai act compliance": "ai_governance",
    "ai compliance": "ai_governance",
    "ai standards and compliance": "ai_governance",
    "ai data governance": "ai_governance",
    "llm safety & policy engineering": "ai_safety",
    "llm security & prompt engineering": "ai_safety",
    "agentic ai security": "ai_safety",
    "differential privacy": "ai_safety",
    "content moderation": "ai_safety",

    # --- NLP & Computer Vision ---
    "natural language processing": "natural_language_processing",
    "nlp and text analytics": "natural_language_processing",
    "natural language classification": "natural_language_processing",
    "speech recognition": "natural_language_processing",
    "speech generation": "natural_language_processing",
    "computer vision": "computer_vision",
    "4d computer vision": "computer_vision",
    "image generation": "generative_ai",
    "3d point cloud generation": "computer_vision",

    # --- DevOps / Git ---
    "github": "git",
    "github actions": "github_actions",
    "gha": "github_actions",
    "k8s": "docker",
    "kubernetes": "docker",
    "kubernetes (gke)": "docker",
    "ci/cd": "ci_cd",
    "microservices architecture": "docker",

    # --- Cursor / IDE ---
    "cursor ai": "cursor",
    "ide": "cursor",

    # --- dbt ---
    "dbt core": "dbt",

    # --- Soft skills / broad concepts mapped loosely ---
    "prompt engineering": "prompt_engineering",
    "prompt caching": "prompt_engineering",
    "enterprise ai": "generative_ai",
    "enterprise ai implementation": "generative_ai",
    "ai integration": "llm_integration",
    "ai application development": "llm_integration",
    "ai automation": "llm_integration",
    "ai-powered analytics": "llm_integration",
    "workflow automation": "llm_integration",
    "code automation": "llm_integration",
    "ai infrastructure": "data_engineering",
    "ai infrastructure engineering": "data_engineering",
    "ai-native infrastructure": "data_engineering",
    "ai compute infrastructure": "data_engineering",
    "gpu": "data_engineering",
    "gpu computing": "data_engineering",
    "gpu programming": "data_engineering",
    "gpu optimization": "data_engineering",
    "gpu infrastructure": "data_engineering",
    "gpu infrastructure and hpc": "data_engineering",
    "tpu": "data_engineering",
    "ai infrastructure & cost optimization": "data_engineering",
    "data privacy": "data_governance",
    "data privacy and compliance": "data_governance",
    "data privacy and protection": "data_governance",
    "data security & privacy": "data_governance",
    "data residency management": "data_governance",
    "ai data science": "data_science",
    "ai/data science": "data_science",

    # --- Other tools/languages ---
    "js": "javascript",
    "node": "javascript",
    "json schema": "api_integration",
    "json-rpc": "api_integration",
    "api development": "api_integration",
    "api management": "api_integration",
    "realtime api development": "api_integration",
    "ollama": "llm_integration",
    "langchain": "llm_integration",
    "polars": "pandas",
    "salesforce": "data_engineering",
}
